# Лекция 3: Библиотеки для глубинного обучения. Примитивы фреймворка PyTorch. 

## На сегодняшней лекции мы разберем, зачем нужны фреймворки для глубинного обучения и как устроены базовые методы и классы PyTorch

In [1]:
import IPython
IPython.display.Image("what is pytorch.png")

#        Пример обучения нейронной сети в numpy

In [2]:
# -*- coding: utf-8 -*-
import numpy as np

# N - размер батча; D_in - размерность входа;
# H - скрытая размероность; D_out размерность выхода.
N, D_in, H, D_out = 64, 1000, 100, 10

# Инициализируем вход и выход из нормального распределения
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Инициализируем веса из нормального распределения
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(500):

    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    
    # Используем функцию активации ReLU
    
    y_pred = h_relu.dot(w2)

    # Считаем функцию потерь
    loss = np.square(y_pred - y).sum()
    print(t, loss)

    # Считаем градиенты
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    
    # Считаем композицию с производной ReLU
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Обновляем веса
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

(0, 23604580.968680754)
(1, 17132458.687414832)
(2, 14724613.97863781)
(3, 14077139.05382486)
(4, 13993458.353950888)
(5, 13678468.368809847)
(6, 12638108.67594438)
(7, 10826698.277541831)
(8, 8556716.218199536)
(9, 6314416.149237566)
(10, 4421502.073223632)
(11, 3009170.1642334703)
(12, 2029871.4356599008)
(13, 1383214.950352312)
(14, 964608.178753102)
(15, 694901.2204824374)
(16, 519005.8882129736)
(17, 401954.5215615315)
(18, 321671.14364388096)
(19, 264722.7469340105)
(20, 222856.43821931048)
(21, 190976.25633489745)
(22, 165898.2569121045)
(23, 145629.86735903707)
(24, 128879.9710888645)
(25, 114745.64685344322)
(26, 102696.23926575425)
(27, 92300.0948599189)
(28, 83254.25184777842)
(29, 75323.6199945831)
(30, 68330.32967807524)
(31, 62134.40790829995)
(32, 56618.66510374424)
(33, 51696.16025649631)
(34, 47288.13975333053)
(35, 43333.14487033505)
(36, 39773.61074966413)
(37, 36562.8922974958)
(38, 33659.2321335741)
(39, 31028.079267530735)
(40, 28638.728563859517)
(41, 26465.15481

(378, 0.00037979158693694743)
(379, 0.00036131516603761006)
(380, 0.00034374077640757835)
(381, 0.00032702315804831463)
(382, 0.00031113286536702304)
(383, 0.0002960098640000008)
(384, 0.00028162249451897485)
(385, 0.0002679411800177103)
(386, 0.0002549250679138611)
(387, 0.0002425446365505579)
(388, 0.0002307654507140303)
(389, 0.00021956209752242777)
(390, 0.0002089083882048568)
(391, 0.00019877063778888797)
(392, 0.0001891284300196779)
(393, 0.00017995399267766352)
(394, 0.00017122723065880226)
(395, 0.00016292477265157735)
(396, 0.0001550273232173034)
(397, 0.00014751389198563566)
(398, 0.0001403688029773357)
(399, 0.00013356771221027244)
(400, 0.00012709849681390758)
(401, 0.00012094505276977564)
(402, 0.00011508919289688317)
(403, 0.00010951836818563537)
(404, 0.00010421891797387703)
(405, 9.917629959377191e-05)
(406, 9.43798833775611e-05)
(407, 8.981517453806878e-05)
(408, 8.547291281721646e-05)
(409, 8.134030943850697e-05)
(410, 7.740862045486875e-05)
(411, 7.366798745029381e-0

# Первая и основная составляющая типичного современного фреймворка для машинного обучения - Tensor

В интерфейсе базовых операций тензор ничем не отличается от __np.ndarray__, но при этом тензоры можно эффективно использовать при обучении на gpu. 

In [3]:
import torch

In [4]:
# Создаем неинициализированный тензор
x = torch.Tensor(5, 3)

In [5]:
x

tensor([[-3.4747e-31,  3.0718e-41,  5.7453e-44],
        [ 0.0000e+00,         nan,  4.5734e-41],
        [ 1.3733e-14,  6.4076e+07,  2.0706e-19],
        [ 7.3909e+22,  2.4176e-12,  1.1625e+33],
        [ 8.9605e-01,  1.1632e+33,  5.6003e-02]])

In [6]:
# Типы
torch.FloatTensor
torch.LongTensor
torch.ByteTensor

torch.ByteTensor

In [7]:
x = torch.Tensor(5, 3).type(torch.FloatTensor)

In [8]:
# инициализируем тензор нормальным распределением
x = torch.randn(5, 3)

In [9]:
x

tensor([[-0.5558,  1.1385,  0.1759],
        [-0.8106,  1.1227,  0.0735],
        [-0.4340, -0.0318,  0.8062],
        [ 0.4370,  1.3536,  0.6669],
        [ 0.2973,  0.6250,  0.4075]])

In [10]:
x.shape

torch.Size([5, 3])

In [11]:
x.size()

torch.Size([5, 3])

In [12]:
y = torch.rand(5, 3)

In [13]:
y

tensor([[0.3693, 0.3256, 0.7766],
        [0.9939, 0.6455, 0.2633],
        [0.6020, 0.6559, 0.7596],
        [0.4719, 0.8973, 0.0617],
        [0.2240, 0.0283, 0.1959]])

In [14]:
# Первый способ сложить 2 тензора
x + y

tensor([[-0.1866,  1.4641,  0.9525],
        [ 0.1833,  1.7682,  0.3369],
        [ 0.1680,  0.6242,  1.5658],
        [ 0.9089,  2.2509,  0.7286],
        [ 0.5214,  0.6533,  0.6034]])

In [15]:
# Второй способ сложить 2 тензора
x.add(y)

tensor([[-0.1866,  1.4641,  0.9525],
        [ 0.1833,  1.7682,  0.3369],
        [ 0.1680,  0.6242,  1.5658],
        [ 0.9089,  2.2509,  0.7286],
        [ 0.5214,  0.6533,  0.6034]])

In [16]:
# А еще можно так:
torch.add(x, y)

tensor([[-0.1866,  1.4641,  0.9525],
        [ 0.1833,  1.7682,  0.3369],
        [ 0.1680,  0.6242,  1.5658],
        [ 0.9089,  2.2509,  0.7286],
        [ 0.5214,  0.6533,  0.6034]])

In [17]:
# Сохраняем выход в тензор result
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)

tensor([[-0.1866,  1.4641,  0.9525],
        [ 0.1833,  1.7682,  0.3369],
        [ 0.1680,  0.6242,  1.5658],
        [ 0.9089,  2.2509,  0.7286],
        [ 0.5214,  0.6533,  0.6034]])

In [18]:
# Перевод из numpy в torch
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b) 

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [19]:
a = torch.randn(5, 3) 
b = torch.randn(3, 4)

In [20]:
# Матричное умножение

torch.mm(a,b)
a.mm(b)

tensor([[ 3.1473, -3.6840, -0.5005,  0.4679],
        [ 2.6542,  3.3224,  0.1924,  2.2143],
        [-1.2828, -0.8363, -0.0380, -0.8142],
        [-0.3732, -0.0418, -0.2528,  0.3589],
        [ 0.6289,  0.5990,  0.7772, -1.0758]])

In [21]:
# для python 3

a @ b

SyntaxError: invalid syntax (<ipython-input-21-6c2aa174fbbf>, line 3)

Поменяем пару строчек в обучении на __numpy__ и код уже можно запускать и на GPU. Например, __x = x.cuda()__

In [22]:
dtype = torch.FloatTensor
# dtype = torch.cuda.FloatTensor # GPU

N, D_in, H, D_out = 64, 1000, 100, 10

x = torch.randn(N, D_in).type(dtype)
y = torch.randn(N, D_out).type(dtype)

w1 = torch.randn(D_in, H).type(dtype)
w2 = torch.randn(H, D_out).type(dtype)

learning_rate = 1e-6
for t in range(500):

    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)

    loss = (y_pred - y).pow(2).sum()
    print(t, loss)

    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)

    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

(0, tensor(24640094.))
(1, tensor(17982938.))
(2, tensor(15061548.))
(3, tensor(13474770.))
(4, tensor(12174690.))
(5, tensor(10676922.))
(6, tensor(8937423.))
(7, tensor(7095913.5000))
(8, tensor(5386531.))
(9, tensor(3952765.5000))
(10, tensor(2847025.2500))
(11, tensor(2039214.3750))
(12, tensor(1469397.1250))
(13, tensor(1074206.7500))
(14, tensor(801410.))
(15, tensor(611721.2500))
(16, tensor(478133.8438))
(17, tensor(382247.0625))
(18, tensor(311950.2188))
(19, tensor(259242.9375))
(20, tensor(218781.6562))
(21, tensor(187035.2656))
(22, tensor(161592.1406))
(23, tensor(140820.2812))
(24, tensor(123590.5078))
(25, tensor(109111.9219))
(26, tensor(96815.9766))
(27, tensor(86281.1250))
(28, tensor(77176.0938))
(29, tensor(69256.5781))
(30, tensor(62320.7734))
(31, tensor(56218.5391))
(32, tensor(50824.9531))
(33, tensor(46041.8984))
(34, tensor(41786.7070))
(35, tensor(37990.6094))
(36, tensor(34594.0703))
(37, tensor(31547.7129))
(38, tensor(28809.7637))
(39, tensor(26344.9980))


(412, tensor(0.0006))
(413, tensor(0.0006))
(414, tensor(0.0006))
(415, tensor(0.0006))
(416, tensor(0.0005))
(417, tensor(0.0005))
(418, tensor(0.0005))
(419, tensor(0.0005))
(420, tensor(0.0005))
(421, tensor(0.0005))
(422, tensor(0.0005))
(423, tensor(0.0005))
(424, tensor(0.0004))
(425, tensor(0.0004))
(426, tensor(0.0004))
(427, tensor(0.0004))
(428, tensor(0.0004))
(429, tensor(0.0004))
(430, tensor(0.0004))
(431, tensor(0.0004))
(432, tensor(0.0004))
(433, tensor(0.0004))
(434, tensor(0.0004))
(435, tensor(0.0003))
(436, tensor(0.0003))
(437, tensor(0.0003))
(438, tensor(0.0003))
(439, tensor(0.0003))
(440, tensor(0.0003))
(441, tensor(0.0003))
(442, tensor(0.0003))
(443, tensor(0.0003))
(444, tensor(0.0003))
(445, tensor(0.0003))
(446, tensor(0.0003))
(447, tensor(0.0003))
(448, tensor(0.0003))
(449, tensor(0.0003))
(450, tensor(0.0003))
(451, tensor(0.0002))
(452, tensor(0.0002))
(453, tensor(0.0002))
(454, tensor(0.0002))
(455, tensor(0.0002))
(456, tensor(0.0002))
(457, tens

In [45]:
torch.cuda.is_avalible

AttributeError: 'module' object has no attribute 'is_avalible'

# Но самое важное в фреймворках - графы вычисления и автоматическое дифференцирование 

In [23]:
# Variable - обертка над тензором, содержащая значения градиента и еще немного полезной информации
import torch
from torch.autograd import Variable
x = Variable(torch.ones(2, 2), requires_grad = True)
x  

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [24]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [25]:
x.grad

In [26]:
# производная операции, которая породила переменную.
x.grad_fn

# Задаем граф вычислений: #

In [27]:
y = x + 2
z = y * y * 2
out = z.mean()
out

tensor(18., grad_fn=<MeanBackward1>)

In [28]:
# Запускаем бэкпроп
# На выходе получаем градиенты из хуков
out.backward()

In [29]:
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [30]:
out.grad == None

True

# Что произошло?

__autograd__ строит ациклический граф вычисления из переменных и операций (функций)
__out.backward__ проходит по всему графу начиная от вершины out и считает градиенты вершин

В __pyTorch__ начиная с версии 0.3 промежуточные градиенты не сохраняются.
Но если мы хотим все-таки увидеть их значения можно использовать
функцию __variable.register_hook(print)__
или использовать __Variable.retain_grad()__

In [31]:
from __future__ import print_function
x = Variable(torch.ones(2, 2), requires_grad = True)
y.register_hook(print)
y = x + 2
z = y * y * 2
z.register_hook(print)
out = z.mean()
out

tensor(18., grad_fn=<MeanBackward1>)

In [32]:
out.backward()

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [33]:
v = torch.autograd.Variable(torch.randn(3), requires_grad=True)
v2 = v+1
v2.retain_grad()
v2.sum().backward()
v2.grad

tensor([1., 1., 1.])

Если мы хотим сохранить значения переменных в графе, то используем retain_graph = True. 
Это может быть нужно, если мы хотим несколько раз подряд сделать backprop

In [34]:
f = Variable(torch.Tensor([2,3]), requires_grad=True)
g = f[0] * f[1]
g.backward(retain_graph=True)
f.grad
g.backward()
f.grad

tensor([6., 4.])

In [35]:
f = Variable(torch.Tensor([2,3]), requires_grad=True)
g = f[0] * f[1]
g.backward()
f.grad
g.backward()
f.grad

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [36]:
x = Variable(torch.ones(2, 2), requires_grad = True)
y = x + 2
y.backward(torch.ones(2, 2), retain_graph=True)
x.grad



tensor([[1., 1.],
        [1., 1.]])

__torch.autograd.Function__ - базовый класс дифференецируемых функций-составных частей графа вычислений

In [37]:
class MyReLU(torch.autograd.Function):

    def forward(self, input):
        # forward pass
        self.save_for_backward(input)
        return input.clamp(min=0)

    def backward(self, grad_output):
        # backward pass
        input, = self.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input



# Снова вернемся к исходной двухслойной сети

In [38]:
import torch
from torch.autograd import Variable

dtype = torch.FloatTensor
# dtype = torch.cuda.FloatTensor # GPU

N, D_in, H, D_out = 64, 1000, 100, 10


x = Variable(torch.randn(N, D_in).type(dtype), requires_grad=False)
y = Variable(torch.randn(N, D_out).type(dtype), requires_grad=False)


w1 = Variable(torch.randn(D_in, H).type(dtype), requires_grad=True)
w2 = Variable(torch.randn(H, D_out).type(dtype), requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)

    loss = (y_pred - y).pow(2).sum()
    print(t, loss.data[0])
    
    # Обнуляем градиенты
    if w1.grad is not None:
        w1.grad.data.zero_()
    if w2.grad is not None:
        w2.grad.data.zero_()

    loss.backward()

    w1.data -= learning_rate * w1.grad.data
    w2.data -= learning_rate * w2.grad.data

/home/alex/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:22: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


0 tensor(32202422.)
1 tensor(27565186.)
2 tensor(28659534.)
3 tensor(30684532.)
4 tensor(29721274.)
5 tensor(24027642.)
6 tensor(15888805.)
7 tensor(8958813.)
8 tensor(4738009.)
9 tensor(2598000.5000)
10 tensor(1579461.2500)
11 tensor(1079568.)
12 tensor(811482.6250)
13 tensor(649229.1875)
14 tensor(539299.4375)
15 tensor(457967.6250)
16 tensor(394232.6250)
17 tensor(342487.1562)
18 tensor(299547.8125)
19 tensor(263368.6250)
20 tensor(232655.0156)
21 tensor(206323.6719)
22 tensor(183609.5000)
23 tensor(163935.0938)
24 tensor(146792.)
25 tensor(131799.4219)
26 tensor(118650.1484)
27 tensor(107058.9453)
28 tensor(96800.5859)
29 tensor(87701.3828)
30 tensor(79603.4844)
31 tensor(72378.0156)
32 tensor(65913.4297)
33 tensor(60117.0391)
34 tensor(54905.2695)
35 tensor(50212.9961)
36 tensor(45979.9336)
37 tensor(42153.2227)
38 tensor(38688.1875)
39 tensor(35543.8125)
40 tensor(32685.9629)
41 tensor(30085.6016)
42 tensor(27716.2617)
43 tensor(25559.1992)
44 tensor(23589.6133)
45 tensor(21788.4

475 tensor(0.0000)
476 tensor(0.0000)
477 tensor(0.0000)
478 tensor(0.0000)
479 tensor(0.0000)
480 tensor(0.0000)
481 tensor(0.0000)
482 tensor(0.0000)
483 tensor(0.0000)
484 tensor(0.0000)
485 tensor(0.0000)
486 tensor(0.0000)
487 tensor(0.0000)
488 tensor(0.0000)
489 tensor(0.0000)
490 tensor(0.0000)
491 tensor(0.0000)
492 tensor(0.0000)
493 tensor(0.0000)
494 tensor(0.0000)
495 tensor(0.0000)
496 tensor(0.0000)
497 tensor(0.0000)
498 tensor(0.0000)
499 tensor(0.0000)


# Наконец, в PyTorch базовые слои нейронных сетей уже реализованы.

### ``Sequental`` - последовательность базовых слоев и функций активаций
### ``Linear(input dimension, output dimension)`` - линейный слой
### ``torch.nn.ReLU``, ``torch.nn.Sigmoid``,``torch.nn.Tanh``, etc. - функции активации
### ``torch.nn.MSELoss`` - среднеквадратичная функция потерь.

In [39]:
from torch.autograd import Variable

N, D_in, D_out = 64, 1000, 10

x = Variable(torch.randn(N, D_in))
y = Variable(torch.randn(N, D_out), requires_grad=False)

model = torch.nn.Sequential(
          torch.nn.Linear(D_in, D_out)
        )

loss_fn = torch.nn.MSELoss(size_average=False)

learning_rate = 1e-4
for t in range(500):
    y_pred = model(x)

    loss = loss_fn(y_pred, y)
    print(t, loss.data[0])

    model.zero_grad()

    loss.backward()

    for param in model.parameters():
        param.data -= learning_rate * param.grad.data

/home/alex/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
/home/alex/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:19: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


0 tensor(804.9891)
1 tensor(513.0012)
2 tensor(332.6003)
3 tensor(219.1593)
4 tensor(146.5921)
5 tensor(99.4063)
6 tensor(68.2490)
7 tensor(47.3803)
8 tensor(33.2193)
9 tensor(23.4956)
10 tensor(16.7473)
11 tensor(12.0192)
12 tensor(8.6783)
13 tensor(6.2997)
14 tensor(4.5948)
15 tensor(3.3655)
16 tensor(2.4745)
17 tensor(1.8255)
18 tensor(1.3509)
19 tensor(1.0024)
20 tensor(0.7456)
21 tensor(0.5559)
22 tensor(0.4154)
23 tensor(0.3109)
24 tensor(0.2331)
25 tensor(0.1751)
26 tensor(0.1317)
27 tensor(0.0992)
28 tensor(0.0748)
29 tensor(0.0565)
30 tensor(0.0427)
31 tensor(0.0323)
32 tensor(0.0245)
33 tensor(0.0186)
34 tensor(0.0141)
35 tensor(0.0107)
36 tensor(0.0081)
37 tensor(0.0062)
38 tensor(0.0047)
39 tensor(0.0036)
40 tensor(0.0027)
41 tensor(0.0021)
42 tensor(0.0016)
43 tensor(0.0012)
44 tensor(0.0009)
45 tensor(0.0007)
46 tensor(0.0005)
47 tensor(0.0004)
48 tensor(0.0003)
49 tensor(0.0002)
50 tensor(0.0002)
51 tensor(0.0001)
52 tensor(0.0001)
53 tensor(0.0001)
54 tensor(0.0001)
55 

459 tensor(1.3245e-12)
460 tensor(1.4041e-12)
461 tensor(1.4344e-12)
462 tensor(1.4154e-12)
463 tensor(1.6021e-12)
464 tensor(1.5656e-12)
465 tensor(1.5191e-12)
466 tensor(1.5755e-12)
467 tensor(1.4050e-12)
468 tensor(1.4999e-12)
469 tensor(1.5113e-12)
470 tensor(1.5429e-12)
471 tensor(1.5383e-12)
472 tensor(1.5895e-12)
473 tensor(1.5112e-12)
474 tensor(1.5410e-12)
475 tensor(1.4900e-12)
476 tensor(1.4071e-12)
477 tensor(1.3452e-12)
478 tensor(1.3053e-12)
479 tensor(1.2399e-12)
480 tensor(1.2436e-12)
481 tensor(1.3824e-12)
482 tensor(1.3740e-12)
483 tensor(1.3574e-12)
484 tensor(1.3747e-12)
485 tensor(1.4241e-12)
486 tensor(1.2522e-12)
487 tensor(1.2750e-12)
488 tensor(1.2953e-12)
489 tensor(1.3012e-12)
490 tensor(1.2809e-12)
491 tensor(1.1692e-12)
492 tensor(1.1518e-12)
493 tensor(1.2602e-12)
494 tensor(1.1936e-12)
495 tensor(1.2653e-12)
496 tensor(1.2655e-12)
497 tensor(1.3452e-12)
498 tensor(1.3891e-12)
499 tensor(1.3904e-12)


In [ ]:
loss_fn(model(x), y)

# А еще в PyTorch есть уже готовые оптимизаторы, такие как GD, SGD, ADAM, etc.

In [40]:
N, D_in, D_out = 64, 1000, 10

x = Variable(torch.randn(N, D_in))
y = Variable(torch.randn(N, D_out), requires_grad=False)

model = torch.nn.Sequential(
          torch.nn.Linear(D_in, D_out),

        )
loss_fn = torch.nn.MSELoss(size_average=False)

learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for t in range(500):
    y_pred = model(x)

    loss = loss_fn(y_pred, y)
    print(t, loss.data[0])

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

/home/alex/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:19: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


0 tensor(799.5036)
1 tensor(785.0867)
2 tensor(770.8203)
3 tensor(756.7070)
4 tensor(742.7487)
5 tensor(728.9475)
6 tensor(715.3053)
7 tensor(701.8236)
8 tensor(688.5041)
9 tensor(675.3480)
10 tensor(662.3566)
11 tensor(649.5311)
12 tensor(636.8722)
13 tensor(624.3809)
14 tensor(612.0577)
15 tensor(599.9034)
16 tensor(587.9182)
17 tensor(576.1025)
18 tensor(564.4565)
19 tensor(552.9801)
20 tensor(541.6733)
21 tensor(530.5359)
22 tensor(519.5674)
23 tensor(508.7676)
24 tensor(498.1357)
25 tensor(487.6713)
26 tensor(477.3734)
27 tensor(467.2412)
28 tensor(457.2739)
29 tensor(447.4704)
30 tensor(437.8296)
31 tensor(428.3503)
32 tensor(419.0314)
33 tensor(409.8716)
34 tensor(400.8694)
35 tensor(392.0236)
36 tensor(383.3326)
37 tensor(374.7950)
38 tensor(366.4092)
39 tensor(358.1737)
40 tensor(350.0869)
41 tensor(342.1472)
42 tensor(334.3528)
43 tensor(326.7022)
44 tensor(319.1937)
45 tensor(311.8255)
46 tensor(304.5959)
47 tensor(297.5032)
48 tensor(290.5457)
49 tensor(283.7215)
50 tensor(

In [42]:
sgd = torch.optim.SGD
adadelta = torch.optim.Adadelta
adagrad = torch.optim.Adagrad
rmsprop = torch.optim.RMSprop

# Сохранение и загрузка модели

In [ ]:
# Сохранение

def save_checkpoint(state, filename='checkpoint.pth.tar'):
    torch.save(state, filename)
epoch =1    
save_checkpoint({
            'epoch': epoch,
            'state_dict': model.state_dict(),
            'optimizer' : optimizer.state_dict(),
        })

In [ ]:
# Пример загрузки

checkpoint = torch.load('checkpoint.pth.tar')
start_epoch = checkpoint['epoch']
model.load_state_dict(checkpoint['state_dict'])
optimizer.load_state_dict(checkpoint['optimizer'])

# Модели с произвольно сложной архитектурой

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer1 = 
        self.layer2 = 

    def forward(self, x):
        pass

## Datasets and Dataloaders

Важная составляющая машинного обучения - работа с данными (загрузка, предобработка, аугментация). __PyTorch__ имеет встроенные средства для этих операций.


Разберем эти операции на примере датасета особых точек лица, находить которые мы будем учиться на семинаре.


Примеры особых точек


left_eye_center, right_eye_center, left_eye_inner_corner, left_eye_outer_corner, right_eye_inner_corner, right_eye_outer_corner, left_eyebrow_inner_end, left_eyebrow_outer_end, right_eyebrow_inner_end, right_eyebrow_outer_end, nose_tip, mouth_left_corner, mouth_right_corner, mouth_center_top_lip, mouth_center_bottom_lip

In [ ]:
%matplotlib inline
from __future__ import print_function, division
import os
import torch
import pandas as pd
from skimage import io, transform
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, utils

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

landmarks_frame = pd.read_csv('dataset/train/face_landmarks.csv')

n = 500
img_name = landmarks_frame.ix[n, 0]
landmarks = landmarks_frame.ix[n, 1:].as_matrix().astype('float')
landmarks = landmarks.reshape(-1, 2)

print('Image name: {}'.format(img_name))
print('Landmarks shape: {}'.format(landmarks.shape))
print('First 4 Landmarks: {}'.format(landmarks[:4]))

def show_landmarks(image, landmarks):
    """Show image with landmarks"""
    plt.imshow(image, cmap='gray')
    plt.scatter(landmarks[:, 0], landmarks[:, 1], s=10, marker='.', c='r')
    plt.pause(0.001)  

plt.figure()
show_landmarks(io.imread(os.path.join('dataset/train/', img_name)),
               landmarks)
plt.show()

Dataset class
-------------

``torch.utils.data.Dataset`` -- абстрактный класс представляющий датасет. 


Для нового класса датасета нужно отнаследоваться от класса Dataset и реализовать следующие функции:


- ``__len__``  так что len(dataset) возвратит длину датасета.


- ``__getitem__``  - индексация, такая что dataset[i] возвратит i-й элемент




In [ ]:
class FaceLandmarksDataset(Dataset):
    """Face Landmarks dataset."""

    def __init__(self, csv_file, root_dir, transform=None):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.landmarks_frame = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.landmarks_frame)

    def __getitem__(self, idx):
        img_name = os.path.join(self.root_dir, self.landmarks_frame.ix[idx, 0])
        image = io.imread(img_name)
        landmarks = self.landmarks_frame.ix[idx, 1:].as_matrix().astype('float')
        landmarks = landmarks.reshape(-1, 2)
        sample = {'image': image, 'landmarks': landmarks}

        if self.transform:
            sample = self.transform(sample)

        return sample

In [ ]:
face_dataset = FaceLandmarksDataset(csv_file='dataset/train/face_landmarks.csv',
                                    root_dir='dataset/train')

fig = plt.figure()

for i in range(len(face_dataset)):
    sample = face_dataset[i]

    print(i, sample['image'].shape, sample['landmarks'].shape)

    ax = plt.subplot(1, 4, i + 1)
    plt.tight_layout()
    ax.set_title('Sample #{}'.format(i))
    ax.axis('off')
    show_landmarks(**sample)

    if i == 3:
        plt.show()
        break

Преобразования (transformations)
----------

Так как часто не все изображения одинакового размера, нужно уметь автоматически приводить их к таковому. Также полезно уметь увеличивать размер датасета (аугментация).

-  ``Rescale``: приведение к определенному размеру
-  ``RandomCrop``: случайный кроп изображения. (вариант аугментации)
-  ``ToTensor``: приведение к тензору




In [ ]:
class Rescale(object):
    """Rescale the image in a sample to a given size.

    Args:
        output_size (tuple or tuple): Desired output size. If tuple, output is
            matched to output_size. If int, smaller of image edges is matched
            to output_size keeping aspect ratio the same.
    """

    def __init__(self, output_size):
        assert isinstance(output_size, (int, tuple))
        self.output_size = output_size

    def __call__(self, sample):
        image, landmarks = sample['image'], sample['landmarks']

        h, w = image.shape[:2]
        if isinstance(self.output_size, int):
            if h > w:
                new_h, new_w = self.output_size * h / w, self.output_size
            else:
                new_h, new_w = self.output_size, self.output_size * w / h
        else:
            new_h, new_w = self.output_size

        new_h, new_w = int(new_h), int(new_w)

        img = transform.resize(image, (new_h, new_w))

        # h and w are swapped for landmarks because for images,
        # x and y axes are axis 1 and 0 respectively
        landmarks = landmarks * [new_w / w, new_h / h]

        return {'image': img, 'landmarks': landmarks}


class RandomCrop(object):
    """Crop randomly the image in a sample.

    Args:
        output_size (tuple or int): Desired output size. If int, square crop
            is made.
    """

    def __init__(self, output_size):
        assert isinstance(output_size, (int, tuple))
        if isinstance(output_size, int):
            self.output_size = (output_size, output_size)
        else:
            assert len(output_size) == 2
            self.output_size = output_size

    def __call__(self, sample):
        image, landmarks = sample['image'], sample['landmarks']

        h, w = image.shape[:2]
        new_h, new_w = self.output_size

        top = np.random.randint(0, h - new_h)
        left = np.random.randint(0, w - new_w)

        image = image[top: top + new_h,
                      left: left + new_w]

        landmarks = landmarks - [left, top]

        return {'image': image, 'landmarks': landmarks}


class ToTensor(object):
    """Convert ndarrays in sample to Tensors."""

    def __call__(self, sample):
        image, landmarks = sample['image'], sample['landmarks']
 
        return {'image': torch.from_numpy(image),
                'landmarks': torch.from_numpy(landmarks)}

Приведем изображение к 68x68 и вырежем случайную область 60x60

In [ ]:
scale = Rescale(68)
crop = RandomCrop(60)
composed = transforms.Compose([Rescale(68),
                               RandomCrop(60)])

# Apply each of the above transforms on sample.
fig = plt.figure()
sample = face_dataset[65]
for i, tsfrm in enumerate([scale, crop, composed]):
    transformed_sample = tsfrm(sample)

    ax = plt.subplot(1, 3, i + 1)
    plt.tight_layout()
    ax.set_title(type(tsfrm).__name__)
    show_landmarks(**transformed_sample)

plt.show()

## Итерирование по датасету

In [ ]:
transformed_dataset = FaceLandmarksDataset(csv_file='dataset/train/face_landmarks.csv',
                                           root_dir='dataset/train/',
                                           transform=transforms.Compose([
                                               Rescale(68),
                                               RandomCrop(60),
                                               ToTensor()
                                           ]))

for i in range(len(transformed_dataset)):
    sample = transformed_dataset[i]

    print(i, sample['image'].size(), sample['landmarks'].size())

    if i == 3:
        break

Для эффективного обучения хотим иметь еще следующие возможности:

-  Батчи
-  Шаффлы
-  Параллельная загрузка

``torch.utils.data.DataLoader`` итератор, который делает все что нам нужно. 

In [ ]:
dataloader = DataLoader(transformed_dataset, batch_size=4,
                        shuffle=True, num_workers=4)


# Helper function to show a batch
def show_landmarks_batch(sample_batched):
    """Show image with landmarks for a batch of samples."""
    images_batch, landmarks_batch = \
            sample_batched['image'], sample_batched['landmarks']
    batch_size = len(images_batch)
    im_size = images_batch.size(2)

    grid = utils.make_grid(images_batch)
    plt.imshow(grid.numpy().transpose(1,0,2).reshape(im_size, -1), cmap="gray")

    for i in range(batch_size):
        plt.scatter(landmarks_batch[i, :, 0].numpy() + i * im_size,
                    landmarks_batch[i, :, 1].numpy(),
                    s=10, marker='.', c='r')

        plt.title('Batch from dataloader')

for i_batch, sample_batched in enumerate(dataloader):
    print(i_batch)

    # observe 4th batch and stop.
    if i_batch == 3:
        plt.figure()
        show_landmarks_batch(sample_batched)
        plt.axis('off')
        plt.ioff()
        plt.show()
        break

In [ ]:
import pandas as pd

In [ ]:
pd.read_csv("dataset/train/face_landmarks.csv")

# Profiling

### В модуле ``torch.autograd.profiler`` реализованы методы для замера времени исполнения различных операций в PyTorch

In [48]:
x = Variable(torch.randn((1, 1)), requires_grad=True)
with torch.autograd.profiler.profile() as prof:
    y = x ** 2
    y.backward()

In [49]:
print(prof)

-----------------------------------  ---------------  ---------------  ---------------  ---------------  ---------------
Name                                        CPU time        CUDA time            Calls        CPU total       CUDA total
-----------------------------------  ---------------  ---------------  ---------------  ---------------  ---------------
pow                                         22.103us          0.000us                1         22.103us          0.000us
torch::autograd::GraphRoot                   0.972us          0.000us                1          0.972us          0.000us
PowBackward0                                34.318us          0.000us                1         34.318us          0.000us
mul                                          6.094us          0.000us                1          6.094us          0.000us
pow                                         10.614us          0.000us                1         10.614us          0.000us
mul                             